[server:vars]
ansible_ssh_private_key_file=/home/sekolahlinux/.ssh/id_rsa
ansible_user=root
ansible_port=22

[server:children]
master
data

[master]
server1 ansible_host=192.168.56.10

[data]
server2 ansible_host=192.168.56.20
server3 ansible_host=192.168.56.30
