---
- name: test
  hosts: server
  become: yes
  vars_files:
    - "./vars.yml"
  vars:
    cluster_name: "elastic-cluster"
    elastic_port: "9200"
    network_host: "0.0.0.0"
  roles:
    - common
    - java
    - elastic

