---
- name: test
  hosts: server
  become: yes
  vars_files:
    - "./vars.yml"
  roles:
    - common
    - java
    - elastic
#  tasks:    
#  - name: Check that you can connect (GET) to a page and it returns a status 200
#    debug: msg="{{ lookup('url', '{{ url }}', split_lines=False) }}"
