---
- name: generate /etc/hosts from inventory
  lineinfile:
    dest: /etc/hosts
    regexp: '.*{{ item }}$'
    line: '{{ hostvars[item].ansible_host }}  {{ hostvars[item].inventory_hostname }}'
    state: present
  when: hostvars[item].inventory_hostname is defined
  with_items: '{{ groups.server }}'
  tags: 'hosts'
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Run the equivalent of "apt-get update" as a separate step
  ansible.builtin.apt:
    update_cache: yes
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Install a list of packages
  ansible.builtin.apt:
    pkg:
    - curl
    - wget
    - net-tools
    - vim
    - htop
    - apt-transport-https

- name: Install python3-pip
  ansible.builtin.apt:
    name: python3-pip
    state: present
    update_cache: yes

- name: ensure pexpect is installed in the playbook python
  ansible.builtin.pip:
    name: pexpect

