---
- name: Add elastic Apt signing key, uses whichever key is at the URL
  ansible.builtin.apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present

- name: Add elastic source repository into sources list
  ansible.builtin.apt_repository:
    repo: deb [signed-by=/usr/share/keyrings/elasticsearch-keyring.gpg] https://artifacts.elastic.co/packages/8.x/apt stable main
    state: present


- name: Update repositories cache and install "elasticsearch" package
  ansible.builtin.apt:
    name: elasticsearch
    update_cache: yes

- name: Setting nodes IPs
  set_fact:
    join_list: "{{ groups['server'] | map('extract', hostvars, ['inventory_hostname']) | list }}"   

- name: Run a command using a templated variable (always use quote filter to avoid injection)
  ansible.builtin.shell: echo "{{ groups.server }}" > /root/akbar.txt
    
